{
  "openapi": "3.0.1",
  "info": { "title": "ticket-bus", "description": "", "version": "1.0.0" },
  "tags": [
    { "name": "Auth" },
    { "name": "Cities" },
    { "name": "Users" },
    { "name": "Vehicles" },
    { "name": "Routes" },
    { "name": "Schedules" }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "Inicio de sesión de usuario registrado",
        "deprecated": false,
        "description": "",
        "operationId": "loginUser",
        "tags": ["Auth"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/Login" },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Usuario autenticado con éxito!",
                      "body": {
                        "user": {
                          "id": 1,
                          "dni": "01212120384",
                          "firstName": "Admin",
                          "lastName": "Admin",
                          "email": "admin@example.com",
                          "miles": 0,
                          "role": "USER"
                        },
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjg5ZjEzNjIzNzU4NzQwMzI2YzQ3YiIsImlhdCI6MTYyNjE2NjUyMiwiZXhwIjoxNjI2MjUyOTIyfQ.4Tz6zJl0b1Z0j6h4v9Ww0kx3q9c5hZy3Dm3z9d7v9wA"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Acceso no autorizado",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "fail",
                      "code": 401,
                      "message": "Usuario o contraseña incorrecta."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error interno del servidor",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "error",
                      "code": 500,
                      "message": "No se pudo autenticar el usuario."
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/cities": {
      "get": {
        "summary": "Obtener todas las ciudades",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Ciudades obtenidas con éxito!",
                      "body": {
                        "cities": [
                          {
                            "id": 1,
                            "name": "Buenos Aires",
                            "createdAt": "2024-02-26T17:16:01.354Z",
                            "updatedAt": "2024-02-26T17:16:01.354Z"
                          },
                          {
                            "id": 2,
                            "name": "Córdoba",
                            "createdAt": "2024-02-26T17:16:01.354Z",
                            "updatedAt": "2024-02-26T17:16:01.354Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      },
      "post": {
        "summary": "Crear ciudad",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string", "description": "name" }
                },
                "required": ["name"]
              },
              "example": { "name": "Palpalá" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Ciudad creada con éxito!",
                      "body": {
                        "id": 40,
                        "name": "Palpalá",
                        "updatedAt": "2024-02-26T19:00:06.865Z",
                        "createdAt": "2024-02-26T19:00:06.865Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Exception: Ciudad repetida",
                    "value": {
                      "status": "fail",
                      "code": 409,
                      "message": "Ya existe una ciudad con el nombre: Rosario"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/users": {
      "get": {
        "summary": "Obtener todos los usuarios",
        "deprecated": false,
        "description": "",
        "operationId": "getAllUsers",
        "tags": ["Users"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Usuarios obtenidos con éxito!",
                      "body": {
                        "users": [
                          {
                            "id": 1,
                            "dni": "01212120384",
                            "firstName": "Adrian",
                            "lastName": "Hueto",
                            "email": "a.hueto@example.com",
                            "miles": 0,
                            "role": "USER"
                          },
                          {
                            "id": 2,
                            "dni": "01212120384",
                            "firstName": "Lucas",
                            "lastName": "Lorenzo",
                            "email": "l.lorenzo@example.com",
                            "miles": 0,
                            "role": "USER"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error interno del servidor",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "error",
                      "code": 500,
                      "message": "Error al obtener los usuarios!"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/vehicles": {
      "get": {
        "summary": "Obtener todos los vehiculos (buses) y sus amenities (servicios)",
        "deprecated": false,
        "description": "",
        "operationId": "getVehiclesAmenities",
        "tags": ["Vehicles"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Vehiculos obtenidos con éxito!",
                      "body": {
                        "vehicles": [
                          {
                            "id": 1,
                            "number": 1,
                            "plate": "QRST90",
                            "totalSeats": 60,
                            "amenities": [
                              "Cargador USB",
                              "WiFi",
                              "Aire Acondicionado"
                            ]
                          },
                          {
                            "id": 2,
                            "number": 2,
                            "plate": "ABCD12",
                            "totalSeats": 40,
                            "amenities": ["WiFi", "TV"]
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error interno del servidor",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "error",
                      "code": 500,
                      "message": "Error al obtener los vehiculos!"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/routes": {
      "get": {
        "summary": "GetAllRoutes",
        "deprecated": false,
        "description": "",
        "tags": ["Routes"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      },
      "post": {
        "summary": "CreateNewRoute",
        "deprecated": false,
        "description": "",
        "tags": ["Routes"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "originId": { "type": "integer" },
                  "destinationId": { "type": "integer" },
                  "duration": { "type": "string" },
                  "distance": { "type": "string" },
                  "price": { "type": "string" }
                },
                "required": [
                  "originId",
                  "destinationId",
                  "duration",
                  "distance",
                  "price"
                ]
              },
              "example": {
                "originId": 1,
                "destinationId": 2,
                "duration": "09:15:00",
                "distance": "700.00",
                "price": "68900.00"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Resgistro de nuevo usuario",
        "deprecated": false,
        "description": "",
        "operationId": "registerUser",
        "tags": ["Auth"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/Register" },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Usuario creado con éxito!",
                      "body": {
                        "user": {
                          "id": 1,
                          "dni": "01245420384",
                          "firstName": "Angel",
                          "lastName": "Diaz",
                          "email": "a.diaz@example.com",
                          "miles": 0,
                          "role": "USER"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflicto en el servidor",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "fail",
                      "code": 409,
                      "message": "El usuario ya existe."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error interno del servidor",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "error",
                      "code": 500,
                      "message": "No se pudo registrar el usuario."
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/schedules/all": {
      "get": {
        "summary": "GetAllSchedules",
        "deprecated": false,
        "description": "",
        "tags": ["Schedules"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    },
    "/cities/id/{id}": {
      "get": {
        "summary": "Obtener ciudad por ID",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID que identifica la ciudad",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Ciudad obtenida con éxito!",
                      "body": {
                        "id": 1,
                        "name": "Buenos Aires",
                        "createdAt": "2024-02-26T17:16:01.354Z",
                        "updatedAt": "2024-02-26T17:16:01.354Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Exception",
                    "value": {
                      "status": "fail",
                      "code": 404,
                      "message": "No se encontró ciudad con el ID: 0"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/schedules": {
      "get": {
        "summary": "GetAvailableSchedules",
        "deprecated": false,
        "description": "",
        "tags": ["Schedules"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      },
      "post": {
        "summary": "CreateNewSchedule",
        "deprecated": false,
        "description": "",
        "tags": ["Schedules"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "originId": { "type": "integer" },
                  "destinationId": { "type": "integer" },
                  "duration": { "type": "string" },
                  "distance": { "type": "string" },
                  "price": { "type": "string" }
                },
                "required": [
                  "originId",
                  "destinationId",
                  "duration",
                  "distance",
                  "price"
                ]
              },
              "example": {
                "originId": 1,
                "destinationId": 2,
                "duration": "09:15:00",
                "distance": "700.00",
                "price": "68900.00"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    },
    "/cities/{id}": {
      "put": {
        "summary": "Actualizar ciudad",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string", "description": "name" }
                },
                "required": ["name"]
              },
              "example": { "name": "Buenos Aires" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Ciudad actualizada con éxito!",
                      "body": {
                        "id": 1,
                        "name": "Buenos Aires",
                        "createdAt": "2024-02-26T17:16:01.354Z",
                        "updatedAt": "2024-02-26T19:18:30.800Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Exception: ID no encontrado",
                    "value": {
                      "status": "fail",
                      "code": 404,
                      "message": "No se encontró ciudad con el ID: 0"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Exception: Nombre repetido",
                    "value": {
                      "status": "fail",
                      "code": 409,
                      "message": "Ya existe una ciudad con el nombre: Buenos Aires"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Eliminar ciudad",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "39",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "status": "success",
                      "code": 200,
                      "message": "Ciudad eliminada con éxito!"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Record Not Found",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ApiResponse" },
                "examples": {
                  "1": {
                    "summary": "Exception: ID no encontrado",
                    "value": {
                      "status": "fail",
                      "code": 404,
                      "message": "No se encontró ciudad con el ID: 10000"
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/routes/{id}": {
      "put": {
        "summary": "UpdateRouteById",
        "deprecated": false,
        "description": "",
        "tags": ["Routes"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "originId": { "type": "integer" },
                  "destinationId": { "type": "integer" },
                  "duration": { "type": "string" },
                  "distance": { "type": "string" },
                  "price": { "type": "string" }
                },
                "required": [
                  "originId",
                  "destinationId",
                  "duration",
                  "distance",
                  "price"
                ]
              },
              "example": {
                "originId": 1,
                "destinationId": 2,
                "duration": "22:15:00",
                "distance": "750.00",
                "price": "68900.00"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "DeleteRouteById",
        "deprecated": false,
        "description": "",
        "tags": ["Routes"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    },
    "/cities/lat": {
      "get": {
        "summary": "Obtener por latitud",
        "deprecated": false,
        "description": "",
        "tags": ["Cities"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    },
    "/schedules/{id}": {
      "put": {
        "summary": "UpdateScheduleById",
        "deprecated": false,
        "description": "",
        "tags": ["Schedules"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "originId": { "type": "integer" },
                  "destinationId": { "type": "integer" },
                  "duration": { "type": "string" },
                  "distance": { "type": "string" },
                  "price": { "type": "string" }
                },
                "required": [
                  "originId",
                  "destinationId",
                  "duration",
                  "distance",
                  "price"
                ]
              },
              "example": {
                "originId": 1,
                "destinationId": 2,
                "duration": "22:15:00",
                "distance": "750.00",
                "price": "68900.00"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "DeleteScheduleById",
        "deprecated": false,
        "description": "",
        "tags": ["Schedules"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "5",
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "type": "object", "properties": {} }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "string" },
          "code": { "type": "integer" },
          "message": { "type": "string" },
          "body": { "type": "object", "properties": {} }
        },
        "required": ["status", "code", "message"]
      },
      "User": {
        "type": "object",
        "properties": {
          "id": { "type": "integer", "examples": [14] },
          "dni": { "type": "string", "examples": ["01245420384"] },
          "firstName": { "type": "string", "examples": ["Angel"] },
          "lastName": { "type": "string", "examples": ["Diaz"] },
          "email": { "type": "string", "examples": ["a.diaz@example.com"] },
          "miles": { "type": "integer", "examples": [0] },
          "role": { "type": "string", "examples": ["USER"] }
        }
      },
      "Register": {
        "type": "object",
        "properties": {
          "dni": { "type": "string", "examples": ["01212120384"] },
          "firstName": { "type": "string", "examples": ["Dani"] },
          "lastName": { "type": "string", "examples": ["Garcia"] },
          "email": { "type": "string", "examples": ["d.garcia@gxmail.com"] },
          "password": {
            "type": "string",
            "format": "password",
            "examples": ["C0ntr4s3ñ4s3gur4"]
          }
        },
        "required": ["dni", "firstName", "lastName", "email", "password"]
      },
      "LoginResponse": { "type": "object", "properties": {} },
      "Login": {
        "type": "object",
        "properties": {
          "email": { "type": "string", "examples": ["usuario@mail.com"] },
          "password": {
            "type": "string",
            "format": "password",
            "examples": ["C0ntr4s3ñ4s3gur4"]
          }
        },
        "required": ["email", "password"]
      }
    },
    "securitySchemes": {}
  },
  "servers": [
    { "url": "http://localhost:3000/api/v1", "description": "Develop Env" }
  ]
}
